# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 552)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(650, 330))
        Dialog.setMaximumSize(QtCore.QSize(650, 560))
        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.deviceLabel = QtWidgets.QLabel(Dialog)
        self.deviceLabel.setObjectName("deviceLabel")
        self.gridLayout_3.addWidget(self.deviceLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.portLabel = QtWidgets.QLabel(Dialog)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_3.addWidget(self.portLabel, 0, 4, 1, 1)
        self.deviceText = QtWidgets.QLineEdit(Dialog)
        self.deviceText.setObjectName("deviceText")
        self.gridLayout_3.addWidget(self.deviceText, 0, 1, 1, 2)
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_3.addWidget(self.resetButton, 0, 7, 1, 1)
        self.baudrateText = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudrateText.sizePolicy().hasHeightForWidth())
        self.baudrateText.setSizePolicy(sizePolicy)
        self.baudrateText.setMaximumSize(QtCore.QSize(70, 16777215))
        self.baudrateText.setObjectName("baudrateText")
        self.gridLayout_3.addWidget(self.baudrateText, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 6, 1, 1)
        self.connectButton = QtWidgets.QPushButton(Dialog)
        self.connectButton.setAutoDefault(True)
        self.connectButton.setDefault(False)
        self.connectButton.setFlat(False)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_3.addWidget(self.connectButton, 0, 8, 1, 1)
        self.statusLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_3.addWidget(self.statusLabel, 1, 0, 1, 3)
        self.sendText = QtWidgets.QLineEdit(Dialog)
        self.sendText.setText("")
        self.sendText.setObjectName("sendText")
        self.gridLayout_3.addWidget(self.sendText, 3, 0, 1, 8)
        spacerItem2 = QtWidgets.QSpacerItem(74, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem2, 1, 8, 1, 1)
        self.consoleText = QtWidgets.QTextEdit(Dialog)
        self.consoleText.setReadOnly(True)
        self.consoleText.setObjectName("consoleText")
        self.gridLayout_3.addWidget(self.consoleText, 2, 0, 1, 9)
        self.sendButton = QtWidgets.QPushButton(Dialog)
        self.sendButton.setEnabled(False)
        self.sendButton.setAutoDefault(True)
        self.sendButton.setDefault(False)
        self.sendButton.setFlat(False)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_3.addWidget(self.sendButton, 3, 8, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.menuList = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuList.sizePolicy().hasHeightForWidth())
        self.menuList.setSizePolicy(sizePolicy)
        self.menuList.setMaximumSize(QtCore.QSize(120, 16777215))
        self.menuList.setObjectName("menuList")
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        self.gridLayout_2.addWidget(self.menuList, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 457, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.clientText = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientText.sizePolicy().hasHeightForWidth())
        self.clientText.setSizePolicy(sizePolicy)
        self.clientText.setMaximumSize(QtCore.QSize(45, 16777215))
        self.clientText.setText("")
        self.clientText.setObjectName("clientText")
        self.gridLayout_4.addWidget(self.clientText, 0, 3, 1, 1)
        self.trayiconCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.trayiconCheckbox.setObjectName("trayiconCheckbox")
        self.gridLayout_4.addWidget(self.trayiconCheckbox, 3, 2, 1, 1)
        self.startupCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.startupCheckbox.setChecked(False)
        self.startupCheckbox.setAutoRepeat(False)
        self.startupCheckbox.setObjectName("startupCheckbox")
        self.gridLayout_4.addWidget(self.startupCheckbox, 0, 0, 1, 1)
        self.serverLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverLabel.sizePolicy().hasHeightForWidth())
        self.serverLabel.setSizePolicy(sizePolicy)
        self.serverLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout_4.addWidget(self.serverLabel, 1, 2, 1, 1)
        self.parsererrCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.parsererrCheckbox.setObjectName("parsererrCheckbox")
        self.gridLayout_4.addWidget(self.parsererrCheckbox, 8, 2, 1, 1)
        self.serverText = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverText.sizePolicy().hasHeightForWidth())
        self.serverText.setSizePolicy(sizePolicy)
        self.serverText.setMaximumSize(QtCore.QSize(45, 16777215))
        self.serverText.setText("")
        self.serverText.setObjectName("serverText")
        self.gridLayout_4.addWidget(self.serverText, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 6, 0, 1, 1)
        self.minimizeCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.minimizeCheckbox.setObjectName("minimizeCheckbox")
        self.gridLayout_4.addWidget(self.minimizeCheckbox, 2, 2, 1, 1)
        self.timestampCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.timestampCheckbox.setObjectName("timestampCheckbox")
        self.gridLayout_4.addWidget(self.timestampCheckbox, 3, 0, 1, 1)
        self.parseroutCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.parseroutCheckbox.setObjectName("parseroutCheckbox")
        self.gridLayout_4.addWidget(self.parseroutCheckbox, 8, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem5, 4, 0, 1, 1)
        self.clientLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientLabel.sizePolicy().hasHeightForWidth())
        self.clientLabel.setSizePolicy(sizePolicy)
        self.clientLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.clientLabel.setObjectName("clientLabel")
        self.gridLayout_4.addWidget(self.clientLabel, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 2, 1, 1, 1)
        self.parserCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.parserCheckbox.setObjectName("parserCheckbox")
        self.gridLayout_4.addWidget(self.parserCheckbox, 7, 0, 1, 1)
        self.parserText = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parserText.sizePolicy().hasHeightForWidth())
        self.parserText.setSizePolicy(sizePolicy)
        self.parserText.setObjectName("parserText")
        self.gridLayout_4.addWidget(self.parserText, 7, 2, 1, 2)
        self.savelastCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.savelastCheckbox.setObjectName("savelastCheckbox")
        self.gridLayout_4.addWidget(self.savelastCheckbox, 2, 0, 1, 1)
        self.reconnectCheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.reconnectCheckbox.setObjectName("reconnectCheckbox")
        self.gridLayout_4.addWidget(self.reconnectCheckbox, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 5, 0, 1, 4)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem7 = QtWidgets.QSpacerItem(292, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(355, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem8, 0, 1, 1, 1)
        self.hideButton = QtWidgets.QPushButton(Dialog)
        self.hideButton.setAutoDefault(True)
        self.hideButton.setDefault(False)
        self.hideButton.setFlat(False)
        self.hideButton.setObjectName("hideButton")
        self.gridLayout.addWidget(self.hideButton, 1, 2, 1, 1)
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setAutoDefault(True)
        self.closeButton.setDefault(False)
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 1, 3, 1, 1)
        self.exportButton = QtWidgets.QPushButton(Dialog)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout.addWidget(self.exportButton, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.hideButton.clicked.connect(Dialog.hide)
        self.sendText.returnPressed.connect(self.sendButton.click)
        self.baudrateText.returnPressed.connect(self.connectButton.click)
        self.deviceText.returnPressed.connect(self.connectButton.click)
        self.closeButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.sendButton, self.deviceText)
        Dialog.setTabOrder(self.deviceText, self.sendText)
        Dialog.setTabOrder(self.sendText, self.baudrateText)
        Dialog.setTabOrder(self.baudrateText, self.consoleText)
        Dialog.setTabOrder(self.consoleText, self.connectButton)
        Dialog.setTabOrder(self.connectButton, self.closeButton)
        Dialog.setTabOrder(self.closeButton, self.hideButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bridge console"))
        self.deviceLabel.setText(_translate("Dialog", "Device"))
        self.portLabel.setText(_translate("Dialog", "Baudrate"))
        self.deviceText.setText(_translate("Dialog", "/dev/rf_bridge"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.baudrateText.setText(_translate("Dialog", "9600"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.statusLabel.setText(_translate("Dialog", "Disconnected"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.menuList.setSortingEnabled(False)
        __sortingEnabled = self.menuList.isSortingEnabled()
        self.menuList.setSortingEnabled(False)
        item = self.menuList.item(0)
        item.setText(_translate("Dialog", "General settings"))
        item = self.menuList.item(1)
        item.setText(_translate("Dialog", "Custom.."))
        self.menuList.setSortingEnabled(__sortingEnabled)
        self.clientText.setPlaceholderText(_translate("Dialog", "0x00"))
        self.trayiconCheckbox.setText(_translate("Dialog", "Enable tray icon"))
        self.startupCheckbox.setText(_translate("Dialog", "Connect on startup"))
        self.serverLabel.setText(_translate("Dialog", "Server address :"))
        self.parsererrCheckbox.setText(_translate("Dialog", "Show parser stderr"))
        self.serverText.setPlaceholderText(_translate("Dialog", "0x00"))
        self.minimizeCheckbox.setText(_translate("Dialog", "Start minimized to tray"))
        self.timestampCheckbox.setText(_translate("Dialog", "Show timestamp"))
        self.parseroutCheckbox.setText(_translate("Dialog", "Show parser stdout"))
        self.clientLabel.setText(_translate("Dialog", "Client address :"))
        self.parserCheckbox.setText(_translate("Dialog", "Parser script"))
        self.savelastCheckbox.setText(_translate("Dialog", "Save last connection"))
        self.reconnectCheckbox.setText(_translate("Dialog", "Resume lost connection"))
        self.hideButton.setText(_translate("Dialog", "Hide"))
        self.closeButton.setText(_translate("Dialog", "Close"))
        self.exportButton.setText(_translate("Dialog", "Export"))

