# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(650, 580))
        Dialog.setMaximumSize(QtCore.QSize(650, 580))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 15, 611, 547))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sendText = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendText.setText("")
        self.sendText.setObjectName("sendText")
        self.gridLayout_3.addWidget(self.sendText, 3, 0, 1, 8)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.portLabel = QtWidgets.QLabel(self.layoutWidget)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_3.addWidget(self.portLabel, 0, 4, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.connectButton.setAutoDefault(True)
        self.connectButton.setDefault(False)
        self.connectButton.setFlat(False)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_3.addWidget(self.connectButton, 0, 8, 1, 1)
        self.deviceText = QtWidgets.QLineEdit(self.layoutWidget)
        self.deviceText.setObjectName("deviceText")
        self.gridLayout_3.addWidget(self.deviceText, 0, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.consoleText = QtWidgets.QTextEdit(self.layoutWidget)
        self.consoleText.setReadOnly(True)
        self.consoleText.setObjectName("consoleText")
        self.gridLayout_3.addWidget(self.consoleText, 2, 0, 1, 9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 4, 0, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.layoutWidget)
        self.sendButton.setEnabled(False)
        self.sendButton.setAutoDefault(True)
        self.sendButton.setDefault(False)
        self.sendButton.setFlat(False)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_3.addWidget(self.sendButton, 3, 8, 1, 1)
        self.deviceLabel = QtWidgets.QLabel(self.layoutWidget)
        self.deviceLabel.setObjectName("deviceLabel")
        self.gridLayout_3.addWidget(self.deviceLabel, 0, 0, 1, 1)
        self.baudrateText = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudrateText.sizePolicy().hasHeightForWidth())
        self.baudrateText.setSizePolicy(sizePolicy)
        self.baudrateText.setMaximumSize(QtCore.QSize(70, 16777215))
        self.baudrateText.setObjectName("baudrateText")
        self.gridLayout_3.addWidget(self.baudrateText, 0, 5, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.layoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_3.addWidget(self.resetButton, 0, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.menuList = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuList.sizePolicy().hasHeightForWidth())
        self.menuList.setSizePolicy(sizePolicy)
        self.menuList.setMaximumSize(QtCore.QSize(120, 16777215))
        self.menuList.setObjectName("menuList")
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        self.gridLayout_2.addWidget(self.menuList, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.layoutWidget1 = QtWidgets.QWidget(self.page)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 471, 212))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lograwCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.lograwCheckbox.setObjectName("lograwCheckbox")
        self.gridLayout_4.addWidget(self.lograwCheckbox, 4, 0, 1, 1)
        self.parserCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.parserCheckbox.setObjectName("parserCheckbox")
        self.gridLayout_4.addWidget(self.parserCheckbox, 8, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_4.addWidget(self.statusLabel, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 2, 1, 1)
        self.clientText = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientText.sizePolicy().hasHeightForWidth())
        self.clientText.setSizePolicy(sizePolicy)
        self.clientText.setMaximumSize(QtCore.QSize(45, 16777215))
        self.clientText.setText("")
        self.clientText.setObjectName("clientText")
        self.gridLayout_4.addWidget(self.clientText, 0, 3, 1, 1)
        self.parseroutCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.parseroutCheckbox.setObjectName("parseroutCheckbox")
        self.gridLayout_4.addWidget(self.parseroutCheckbox, 9, 0, 1, 1)
        self.parserText = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parserText.sizePolicy().hasHeightForWidth())
        self.parserText.setSizePolicy(sizePolicy)
        self.parserText.setObjectName("parserText")
        self.gridLayout_4.addWidget(self.parserText, 8, 2, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem6, 5, 0, 1, 1)
        self.savelastCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.savelastCheckbox.setObjectName("savelastCheckbox")
        self.gridLayout_4.addWidget(self.savelastCheckbox, 1, 2, 1, 3)
        self.lograwText = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lograwText.sizePolicy().hasHeightForWidth())
        self.lograwText.setSizePolicy(sizePolicy)
        self.lograwText.setObjectName("lograwText")
        self.gridLayout_4.addWidget(self.lograwText, 4, 2, 1, 3)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 6, 0, 1, 5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 1, 1, 1)
        self.timestampCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.timestampCheckbox.setObjectName("timestampCheckbox")
        self.gridLayout_4.addWidget(self.timestampCheckbox, 3, 2, 1, 1)
        self.reconnectCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.reconnectCheckbox.setObjectName("reconnectCheckbox")
        self.gridLayout_4.addWidget(self.reconnectCheckbox, 2, 2, 1, 1)
        self.parsererrCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.parsererrCheckbox.setObjectName("parsererrCheckbox")
        self.gridLayout_4.addWidget(self.parsererrCheckbox, 9, 2, 1, 1)
        self.startupCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.startupCheckbox.setChecked(False)
        self.startupCheckbox.setAutoRepeat(False)
        self.startupCheckbox.setObjectName("startupCheckbox")
        self.gridLayout_4.addWidget(self.startupCheckbox, 1, 0, 1, 1)
        self.minimizeCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.minimizeCheckbox.setObjectName("minimizeCheckbox")
        self.gridLayout_4.addWidget(self.minimizeCheckbox, 2, 0, 1, 1)
        self.trayiconCheckbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.trayiconCheckbox.setObjectName("trayiconCheckbox")
        self.gridLayout_4.addWidget(self.trayiconCheckbox, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, -1, 431, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_6.addWidget(self.lineEdit_5, 1, 1, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_2, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_6.addWidget(self.lineEdit_2, 2, 1, 1, 2)
        self.logcsvCheckbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.logcsvCheckbox.setObjectName("logcsvCheckbox")
        self.gridLayout_6.addWidget(self.logcsvCheckbox, 4, 0, 2, 1)
        self.logcsvText = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.logcsvText.setObjectName("logcsvText")
        self.gridLayout_6.addWidget(self.logcsvText, 4, 1, 2, 2)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, -1, 431, 50))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_8.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget_4)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_3, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem9 = QtWidgets.QSpacerItem(292, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 0, 1, 1)
        self.hideButton = QtWidgets.QPushButton(self.layoutWidget)
        self.hideButton.setAutoDefault(True)
        self.hideButton.setDefault(False)
        self.hideButton.setFlat(False)
        self.hideButton.setObjectName("hideButton")
        self.gridLayout.addWidget(self.hideButton, 1, 1, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.closeButton.setAutoDefault(True)
        self.closeButton.setDefault(False)
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(13, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem10, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.hideButton.clicked.connect(Dialog.hide)
        self.sendText.returnPressed.connect(self.sendButton.click)
        self.baudrateText.returnPressed.connect(self.connectButton.click)
        self.deviceText.returnPressed.connect(self.connectButton.click)
        self.closeButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.sendButton, self.deviceText)
        Dialog.setTabOrder(self.deviceText, self.sendText)
        Dialog.setTabOrder(self.sendText, self.baudrateText)
        Dialog.setTabOrder(self.baudrateText, self.consoleText)
        Dialog.setTabOrder(self.consoleText, self.connectButton)
        Dialog.setTabOrder(self.connectButton, self.closeButton)
        Dialog.setTabOrder(self.closeButton, self.hideButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bridge console"))
        self.portLabel.setText(_translate("Dialog", "Baudrate"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.deviceText.setText(_translate("Dialog", "/dev/rf_bridge"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.deviceLabel.setText(_translate("Dialog", "Device"))
        self.baudrateText.setText(_translate("Dialog", "9600"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.menuList.setSortingEnabled(False)
        __sortingEnabled = self.menuList.isSortingEnabled()
        self.menuList.setSortingEnabled(False)
        item = self.menuList.item(0)
        item.setText(_translate("Dialog", "General settings"))
        item = self.menuList.item(1)
        item.setText(_translate("Dialog", "Heat controller"))
        item = self.menuList.item(2)
        item.setText(_translate("Dialog", "Light"))
        self.menuList.setSortingEnabled(__sortingEnabled)
        self.lograwCheckbox.setText(_translate("Dialog", "Log console output"))
        self.parserCheckbox.setText(_translate("Dialog", "Parser script"))
        self.statusLabel.setText(_translate("Dialog", "Disconnected"))
        self.label_7.setText(_translate("Dialog", "Set client address :"))
        self.clientText.setPlaceholderText(_translate("Dialog", "0x00"))
        self.parseroutCheckbox.setText(_translate("Dialog", "Show parser stdout"))
        self.savelastCheckbox.setText(_translate("Dialog", "Save last connection"))
        self.timestampCheckbox.setText(_translate("Dialog", "Show timestamp"))
        self.reconnectCheckbox.setText(_translate("Dialog", "Resume lost connection"))
        self.parsererrCheckbox.setText(_translate("Dialog", "Show parser stderr"))
        self.startupCheckbox.setText(_translate("Dialog", "Connect on startup"))
        self.minimizeCheckbox.setText(_translate("Dialog", "Start minimized to tray"))
        self.trayiconCheckbox.setText(_translate("Dialog", "Enable tray icon"))
        self.label_2.setText(_translate("Dialog", "Command"))
        self.label_6.setText(_translate("Dialog", "Durée (min)"))
        self.lineEdit_4.setText(_translate("Dialog", "10;10;15"))
        self.label_4.setText(_translate("Dialog", "Value"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Heat ramps"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Desired temp"))
        self.label_5.setText(_translate("Dialog", "Temperature (C)"))
        self.lineEdit_2.setText(_translate("Dialog", "30;40;55"))
        self.logcsvCheckbox.setText(_translate("Dialog", "Log temp. (csv)"))
        self.label.setText(_translate("Dialog", "Value"))
        self.label_3.setText(_translate("Dialog", "Command"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Light on"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Light off"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Strobe"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "PWM"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "Flash"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "Rising"))
        self.hideButton.setText(_translate("Dialog", "Hide"))
        self.closeButton.setText(_translate("Dialog", "Close"))

